    <style>
        #weather {
        border-collapse: collapse;
        font-family: "Trebuchet MS",Arial,Helvetica,sans-serif;
        width: 100%;
        }
        #weather td, #customers th {
            border: 1px solid #98BF21;
            font-size: 1.2em;
            padding: 3px 7px 2px;
        }
        #weather th {
            background-color: #A7C942;
            color: #FFFFFF;
            font-size: 1.4em;
            padding-bottom: 4px;
            padding-top: 5px;
            text-align: center;
        }
        #weather tr.alt td {
            background-color: #EAF2D3;
            color: #000000;
        }

</style>
<br/><br/><br/>
    <table id="weather" name="weather" style="width: 10%" align="center">
        <tr>
            <th>Welcome to Fuji!</th>
        </tr>
        <tr>
            <td>
                <img src="https://github.com/workplacesystems/WPS-POC2/blob/master/application/views/images/workplace.png?raw=true">
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <p>Choose from one of the following options:</p>
                <p>
                    <ul>
                        <li><a href="/weather">Get the Weather for your postcode</a></li>
                        <li><a href="/weather">Sign In</a></li>
                        <li><a href="/weather">Contact Us</a></li>
                    </ul>
                </p>
            </td>
        </tr>        
    </table>