    <style>
        #weather {
        border-collapse: collapse;
        font-family: "Trebuchet MS",Arial,Helvetica,sans-serif;
        width: 100%;
        }
        #weather td, #customers th {
            border: 1px solid #98BF21;
            font-size: 1.2em;
            padding: 3px 7px 2px;
        }
        #weather th {
            background-color: #A7C942;
            color: #FFFFFF;
            font-size: 1.4em;
            padding-bottom: 4px;
            padding-top: 5px;
            text-align: center;
        }
        #weather tr.alt td {
            background-color: #EAF2D3;
            color: #000000;
        }

</style>
<br/><br/><br/>
    <table id="weather" name="weather" style="width: 30%" align="center">
        <tr><th><h1>Welcome to Fuji!</h1></th></tr>
        <tr><td><img src="https://github.com/workplacesystems/WPS-POC2/blob/master/application/views/images/workplace.png?raw=true"></td></tr>
        <tr>
            <td colspan="2">Choose from one of the following options:</td>
        </tr>
        <tr>
            <td colspan="2">
                <ul>
                    <li><a href="/weather">Get the Weather for your postcode</a></li>
                </ul>
            </td>
        </tr>        
    </table>