<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <style>
        #weather {
        border-collapse: collapse;
        font-family: "Trebuchet MS",Arial,Helvetica,sans-serif;
        width: 100%;
        }
        #weather td, #customers th {
            border: 1px solid #98BF21;
            font-size: 1.2em;
            padding: 3px 7px 2px;
        }
        #weather th {
            background-color: #A7C942;
            color: #FFFFFF;
            font-size: 1.4em;
            padding-bottom: 4px;
            padding-top: 5px;
            text-align: center;
        }
        #weather tr.alt td {
            background-color: #EAF2D3;
            color: #000000;
        }

</style>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Scheduling: Get the weather for your area</title>
</head>
    <body>
        <table style="width: 75%" name="weather" id="weather" align="center">
            <tr>
                <th><a href="/">Home</a></th>
                <th>Schedules</th>
                <th>Offering</th>
                <th>Staff<th>
                <th>Admin</th>
                <th>Help</th>
            </tr>
        </table>
        <br/>
        <br/>
        <form method="post" name="weather" id="weather">
        <table style="width: 25%" name="weather" id="weather" align="center">
            <tr>
                <td>Enter your postcode:</td>
                <td><input type="text" id="postcode" name="postcode" /></td>
            </tr>
            <tr>
                <td colspan="2" align="left"><input type="submit" id="submit" name="submit" value="Get Weather" /></td>
            </tr>              
        </table>
        <br/>
        <? if ($this->postcode != '' && !empty($this->weatherData)) { ?>
        <div><h1>Latest weather for postcode <?=$this->postcode?>:</h1></div>
                <table width="100%" class="weather" id="weather">
                    <tr>
                        <? foreach($this->weatherHeaders as $header) { ?>
                            <th align="center"><?=$header?></th>
                        <? } ?>
                    </tr>                    
                    <tr>
                        <? foreach($this->weatherData as $data) { ?>
                            <?
                            $img = strpos($data, ".png") ? "<img src='".$data."'/>" : null; 
                            if ($img) {?>
                                <td align="center"><?=$img?></td>
                            <? } else { ?>
                                <td align="center"><?=$data?></td>
                            <? } ?>
                        <? } ?>
                    </tr>
                </table>
        <?}?>
    </form>
</body>
</html>
