<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <style>
        #weather {
        border-collapse: collapse;
        font-family: "Trebuchet MS",Arial,Helvetica,sans-serif;
        width: 100%;
        }
        #weather td, #customers th {
            border: 1px solid #98BF21;
            font-size: 1.2em;
            padding: 3px 7px 2px;
        }
        #weather th {
            background-color: #A7C942;
            color: #FFFFFF;
            font-size: 1.4em;
            padding-bottom: 4px;
            padding-top: 5px;
            text-align: left;
        }
        #weather tr.alt td {
            background-color: #EAF2D3;
            color: #000000;
        }

</style>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Scheduling: Get the weather for your area</title>
</head>
    <body style="background-color: #CCFF99">
        <table width="100%" name="weather" id="weather">
            <tr>
                <td width="50" align="center">Home</td>
                <td width="50" align="center">Schedules</td>
                <td width="50" align="center">Offering</td>
                <td width="50" align="center">Staff</td>
                <td width="50" align="center">Admin</td>
                <td width="50" align="center">Help</td>
            </tr>
        </table>
        <br/>
        <br/>
        <form method="post" name="weather" id="weather">
        <table cellpadding="2">
            <tr>
                <td>Enter your Postcode:</td>
                <td><input type="text" id="postcode" name="postcode"></input></td>
            </tr> 
            <tr>
                <td></td>
                <td><input type="submit" id="submit" name="submit" value="Get Weather" /></td>
            </tr>                
        </table>
        <br/>
        <br/>
        <? if ($this->postcode != '') { ?>
            <h1>Latest weather for postcode <?=$this->postcode?>:</h1>
            <br/>
                <table width="100%" class="weather" id="weather">
                    <tr>
                        <? foreach($this->weatherHeaders as $header) { ?>
                            <th align="center"><?=$header?></th>
                        <? } ?>
                    </tr>                    
                    <tr>
                        <td width="50" align="center">&nbsp;</td>
                        <td width="50" align="center">&nbsp;</td>
                        <td width="50" align="center">&nbsp;</td>
                        <td width="50" align="center">&nbsp;</td>
                        <td width="50" align="center">&nbsp;</td>
                        <td width="50" align="center">&nbsp;</td>
                    </tr>
                </table>
        <?}?>
    </form>
</body>
</html>
