<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Scheduling: Get the weather for your area</title>
</head>
    <body style="background-color: #CCFF99">
        <table width="50%" style="border: 1px solid gray">
            <tr>
                <td width="50" align="center">Home</td>
                <td width="50" align="center">Schedules</td>
                <td width="50" align="center">Offering</td>
                <td width="50" align="center">Staff</td>
                <td width="50" align="center">Admin</td>
                <td width="50" align="center">Help</td>
            </tr>
        </table>
        <form method="post" action="weather/getweather" name="weather" id="weather">
        <table cellpadding="2">
            <tr>
                <td>Enter your Postcode:</td>
                <td><input type="text" id="postcode" name="postcode"></input></td>
            </tr> 
            <tr>
                <td></td>
                <td><input type="submit" id="submit" name="submit" value="Get Weather" /></td>
            </tr>                

        </table>
    </form>
</body>
</html>
