<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <style>
        #weather {
        border-collapse: collapse;
        font-family: "Trebuchet MS",Arial,Helvetica,sans-serif;
        width: 100%;
        }
        #weather td, #customers th {
            border: 1px solid #98BF21;
            font-size: 1.2em;
            padding: 3px 7px 2px;
        }
        #weather th {
            background-color: #A7C942;
            color: #FFFFFF;
            font-size: 1.4em;
            padding-bottom: 4px;
            padding-top: 5px;
            text-align: center;
        }
        #weather tr.alt td {
            background-color: #EAF2D3;
            color: #000000;
        }

</style>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Scheduling: Get the weather for your area</title>
</head>
    <body>
        <table style="width: 75%" name="weather" id="weather" align="center">
            <tr>
                <th><a href="/">Home Link</a></th>
                <th>Schedules</th>
                <th>Offering</th>
                <th>Staff<th>
                <th>Admin</th>
                <th>Help</th>
            </tr>
        </table>
        <br/>
        <div><h1>Create New Schedules</h1></div>
        <br/>
        <form method="post" name="schedules" id="schedules">
        <table style="width: 25%" name="weather" id="weather" align="center">
            <tr>
                <td>Description:</td>
                <td><input type="text" id="description" name="description" /></td>
            </tr>
            <tr>
                <td>Start Date:</td>
                <td><input type="text" id="start_date" name="start_date" /></td>
            </tr>
            <tr>
                <td>End Date:</td>
                <td><input type="text" id="end_date" name="end_date" /></td>
            </tr>            
            <tr>
                <td colspan="2" align="left"><input type="submit" id="submit" name="submit" value="Add" /></td>
            </tr>              
        </table>
        <br/>
        <? if (!empty($this->schedules)) { ?>
        <div><h1>Your schedules:</h1></div>
                <table width="50%" class="schedules" id="schedules" align="center">
                    <tr>
                        <th>Description</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                    </tr>                    
                    <tr>
                    <? foreach($this->schedules as $schedule) { ?>
                        <td align="left"><?=$schedule['description']?></td>
                        <td align="left"><?=$schedule['start_date']?></td>
                        <td align="left"><?=$schedule['end_date']?></td>
                    <? } ?>
                    </tr>
                </table>
        <?}?>
    </form>
</body>
</html>
